cluster.name: "docker-cluster"
network.host: 0.0.0.0

discovery.seed_hosts: ["elasticsearch"]

xpack.security.enabled: true
xpack.monitoring.collection.enabled: true
xpack.security.transport.ssl.enabled: true
